### PR TITLE
Fix besnappy call change 

### PR DESCRIPTION
**Pull request by imsickofmaps**

### CODE REVIEW

**Comment by imsickofmaps** [comment]
http://prd-sentry.za.prk-host.net/ndoh/ndoh-production/group/44484/

**Comment by imsickofmaps** [comment]
Tested on commandline so self :+1: to stop the blackholing of tickets quickly. Need to complete the move to the snappy-bouncer app.

**Comment by hodgestar** [comment]
It looks like the standalone snappy bouncer suffers from this problem too.

**Comment by imsickofmaps** [comment]
@hodgestar poor test coverage obviously :disappointed: ... @jerith did open a ticket to improve that.

**Pull request merged**
