### PR TITLE
Send more metrics to metric store

### PR DESCRIPTION
**Pull request by imsickofmaps**
Triggers:
- [x] MessageSet Transition (auto)

Scheduled:
- [x] Total all-time per set
- [x] Total active per set
- [x] Total all-time per lang
- [x] Total active per lang
- [ ] Snappy Stats

### CODE REVIEW

**Comment by imsickofmaps** [comment]
@gsvr review please

**Comment by gsvr** [comment]
:+1:

**Comment by imsickofmaps** [comment]
quick recheck of the last commit please @gsvr

**Comment by gsvr** [comment]
@imsickofmaps :+1:

**Pull request merged**
