### PR TITLE
Downloadable Snappybouncer

### PR DESCRIPTION
**Pull request by imsickofmaps**
JIRA: https://praekelt.atlassian.net/browse/NDOH-140

### CODE REVIEW

**Comment by imsickofmaps** [comment]
@gsvr review please

**Comment by gsvr** [comment]
:+1:

**Comment by hodgestar** [comment]
Can I move this to the standalone snappy bouncer for you?

**Comment by imsickofmaps** [comment]
I didn't immediately do this because of the timeliness request, and that it was using a shared action. If you are willing to, you're now a contributor on that team

**Pull request merged**
