### PR TITLE
additional schedule settings

### PR DESCRIPTION
**Pull request by imsickofmaps**

### CODE REVIEW

**Comment by imsickofmaps** [comment]
@hodgestar minor for review

**Comment by hodgestar** [comment]
The changes look fine but I question whether `initial_data` is the correct place for this, because any changes made won't affect databases being updated (when I assuming all existing setups should get the updates)?

The periodic celery tasks can also be configured in `settings.py`. I wonder if that would be a better place for them?

Sorry, should have raised this earlier when the `djcelery` configs first landed.

**Comment by imsickofmaps** [comment]
We're not anywhere public with this setup so I'll be blowing up and rebuilding the DB in QA so that's why I stuck this stuff in initial_data for now. This _should_ be the last time this dataset changes :wink: 

I know you can setup periodic tasks in settings.py but I don't think you can do crontab driven ones because they're not in the default djcelery stuff (hence me creating, then using them, with this initial data method).

**Comment by hodgestar** [comment]
:+1:

**Comment by hodgestar** [comment]
I'm reasonably certain we have crontab ones in our Vumi Go settings.

**Pull request merged**
