### PR TITLE
Add single message editing to CI

### PR DESCRIPTION
**Pull request by imsickofmaps**
- [x] Select protocol
- [x] Select language
- [x] Enter message number
- [x] Edit content
- [x] Save

### CODE REVIEW

**Comment by imsickofmaps** [comment]
@gsvr - needs tests HTTP POST tests, but can you just check the flow

**Comment by gsvr** [comment]
@imsickofmaps Looks good so far

**Comment by imsickofmaps** [comment]
@gsvr ready for re-review, modified flow and tests \o/

**Comment by gsvr** [comment]
:+1:

**Pull request merged**
